version: '3.7'
services:
  web:
    build:
      context: './config/docker/php'
      dockerfile: './Dockerfile'
    ports:
      - '8080:80'
      - '9090:8080'
    volumes:
      - './server/html:/var/www/html'
      - './server/public:/var/www/html/public'
      - './server/private:/var/www/private'
    environment:
      ENVIRONMENT: 'dev'
      DB_SERVER: database
      DB_DATABASE: craft
      DB_USER: craft
      DB_PASSWORD: craft
      DB_TABLE_PREFIX: fff_
      DEFAULT_SITE_URL: http://localhost:8080
      NL_SITE_URL: http://localhost:8080/nl
      EN_SITE_URL: http://localhost:8080/

  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: password
      UPLOAD_LIMIT: 64M
    links:
      - database:database

  database:
    image: mariadb:10.5.8
    ports:
      - '8082:3306'
    volumes:
      - ./server/database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: craft
      MYSQL_USER: craft
      MYSQL_PASSWORD: craft
